[book]
authors = ["XCollective"]
language = "en"
multilingual = false
src = "src"
title = "XCollective Knowledge Base"
description = "The accumulated knowledge of the XCollective community."

[output.html]
mathjax-support = true
site-url = "/x-collective/"
git-repository-url = "https://github.com/jaredcosulich/x-collective/tree/main"
edit-url-template = "https://github.com/jaredcosulich/x-collective/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"